### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Alide930** [liutongkun/FAIR#4]
Sorry to bother you, but how can I fix this issue?

python train.py --gpu_id 0 --obj_id -1 --lr 0.0001 --bs 8 --epochs 1 --data_path ./datasets/MVTec-AD/ --anomaly_source_path ./datasets/dtd/images --log_path ./checkpoints_mvtecad_self/ --checkpoint_path ./checkpoints_mvtecad_self/ --visualize
Using cuda
Epoch: 0
Traceback (most recent call last):
  File "D: \FAIR-main\train.py", line 143, in <module>
    train_on_device(picked_classes, args)
  File "D:\FAIR-main\train.py", line 57, in train_on_device
    for i_batch, sample_batched in enumerate(dataloader):
  File "D:\anaconda3\envs\fair\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\fair\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\envs\fair\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\anaconda3\envs\fair\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3\envs\fair\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\envs\fair\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\fair\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\FAIR-main\data_loaderbhpfnewaug.py", line 259, in __getitem__
    image, augmented_image, anomaly_mask, has_anomaly,auggray = self.transform_image(self.image_paths[idx],
  File "D:\FAIR-main\data_loaderbhpfnewaug.py", line 224, in transform_image
    augmented_image, anomaly_mask, has_anomaly = self.augment_image(augmented_image, anomaly_source_path)
  File "D:\FAIR-main\data_loaderbhpfnewaug.py", line 144, in augment_image
    anomaly_img_augmented = aug(image=anomaly_source_img)
  File "D:\anaconda3\envs\fair\lib\site-packages\imgaug\augmenters\meta.py", line 2008, in __call__
    return self.augment(*args, **kwargs)
  File "D:\anaconda3\envs\fair\lib\site-packages\imgaug\augmenters\meta.py", line 1979, in augment
    batch_aug = self.augment_batch_(batch, hooks=hooks)
  File "D:\anaconda3\envs\fair\lib\site-packages\imgaug\augmenters\meta.py", line 641, in augment_batch_
    batch_inaug = self._augment_batch_(
  File "D:\anaconda3\envs\fair\lib\site-packages\imgaug\augmenters\meta.py", line 3124, in _augment_batch_
    batch = self[index].augment_batch_(
  File "D:\anaconda3\envs\fair\lib\site-packages\imgaug\augmenters\meta.py", line 641, in augment_batch_
    batch_inaug = self._augment_batch_(
  File "D:\anaconda3\envs\fair\lib\site-packages\imgaug\augmenters\color.py", line 2470, in _augment_batch_
    image_hsv = self._transform_image_cv2(
  File "D:\anaconda3\envs\fair\lib\site-packages\imgaug\augmenters\color.py", line 2501, in _transform_image_cv2
    table_hue = cls._LUT_CACHE[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by liutongkun** [comment]
Hi, you can refer to https://github.com/yu4u/age-estimation-pytorch/issues/21#issuecomment-1244821328

![image](https://github.com/user-attachments/assets/d22ab8a0-d18b-47b0-8f8b-7240daf26c79)
Replace  '_cv2' with '_numpy' for Window system

**Comment by Alide930** [comment]
> Hi, you can refer to [yu4u/age-estimation-pytorch#21 (comment)](https://github.com/yu4u/age-estimation-pytorch/issues/21#issuecomment-1244821328)
> 
> ![image](https://private-user-images.githubusercontent.com/59155313/397351539-d22ab8a0-d18b-47b0-8f8b-7240daf26c79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODEwNzEsIm5iZiI6MTczNDY4MDc3MSwicGF0aCI6Ii81OTE1NTMxMy8zOTczNTE1MzktZDIyYWI4YTAtZDE4Yi00N2IwLThmOGItNzI0MGRhZjI2Yzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA3NDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ODg5OTdiNjE4ZmUzNTRjZjRkOTc0OTU4OGI4ZjA1YjRkMTM5MGNhNzIzMmViYjBiMGQyYjY0OTE3MmI1NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yhD66lC_cErW2u2G7Y9jbPYQeLyu7Lq1W8BR9xYbV04) Replace '_cv2' with '_numpy' for Window system

Thank you very much for your help. I have solved the problem.
